name: tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ["8.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: mbstring, json, tokenizer, xml, ctype, dom, intl
          coverage: xdebug

      - name: Validate composer.json
        run: composer validate --strict

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run PHPUnit with coverage
        run: vendor/bin/phpunit --coverage-clover build/coverage.xml

      - name: Parse coverage percent to env
        id: coverage
        run: |
          php -r '
          $f = "build/coverage.xml";
          $xml = new SimpleXMLElement(file_get_contents($f));
          $m = $xml->project->metrics;
          $pct = ((int)$m["statements"]) > 0 ? ((int)$m["coveredstatements"] / (int)$m["statements"]) * 100 : 0;
          $pct = round($pct, 2);
          echo "coverage=$pct" . PHP_EOL;
          ' >> $GITHUB_OUTPUT

      - name: Update Coverage Badge (Gist)
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ${{ secrets.COVERAGE_GIST_ID }}
          filename: notify-coverage.json
          label: coverage
          message: ${{ steps.coverage.outputs.coverage }}%
          color: ${{ steps.coverage.outputs.coverage < 80 && 'red' || (steps.coverage.outputs.coverage < 90 && 'yellow' || 'brightgreen') }}
